export const SET_TWEETS = "SET_TWEETS";
export const SET_FILTERED_TWEETS = "SET_FILTERED_TWEETS";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_APP_MESSAGE = "SET_APP_MESSAGE";
export const SET_IS_XHR_RUNNING = "SET_IS_XHR_RUNNING";
export const SET_IS_NEW_SEARCH = "SET_IS_NEW_SEARCH";
